name = "FastSolversForWeightedTV"
uuid = "3521e485-16e8-49c3-934a-dec609b578e8"
authors = ["Gabrio Rizzuti"]
version = "1.0.0"

[deps]
AbstractLinearOperators = "bb902dec-a34b-4f3c-9707-4856bea60ee0"
AbstractProximableFunctions = "9ed10759-246d-4065-822b-90d32585fe69"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"

[compat]
julia = "1.11"

[sources]
AbstractLinearOperators = { url = "https://github.com/oscarvanderheide/AbstractLinearOperators.jl" }
AbstractProximableFunctions = { url = "https://github.com/oscarvanderheide/AbstractProximableFunctions" }

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "CUDA"]
